version: '3.8'

services:
  api:
    image: api
    build:
      context: ./AudioToSearch/
      dockerfile: ./src/AudioToSearch.Api/Dockerfile
    #environment:
    #  - ConnectionStrings__Redis=redis:6379
    ports:
      - "5023:8080"
    depends_on:
      - db
      
  db:
    image: pgvector/pgvector:pg14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: