// <auto-generated />
using System;
using AudioToSearch.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioToSearch.Infra.Data.Migrations
{
    [DbContext(typeof(AudioToSearchContext))]
    [Migration("20240810005030_AddTranscricaoes")]
    partial class AddTranscricaoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioEntity", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UId");

                    b.ToTable("CatalogarAudioEntity");
                });

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioTranscricaoEntity", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Final")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UIdCatalogarAudio")
                        .HasColumnType("TEXT");

                    b.HasKey("UId");

                    b.HasIndex("UIdCatalogarAudio");

                    b.ToTable("CatalogarAudioTranscricaoEntity");
                });

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioTranscricaoEntity", b =>
                {
                    b.HasOne("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioEntity", "CatalogarAudio")
                        .WithMany("Transcricaoes")
                        .HasForeignKey("UIdCatalogarAudio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogarAudio");
                });

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioEntity", b =>
                {
                    b.Navigation("Transcricaoes");
                });
#pragma warning restore 612, 618
        }
    }
}
