// <auto-generated />
using System;
using AudioToSearch.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AudioToSearch.Infra.Data.Migrations
{
    [DbContext(typeof(AudioToSearchContext))]
    [Migration("20240820002446_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioEntity", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UId");

                    b.ToTable("CatalogarAudioEntity");
                });

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioTranscricaoEntity", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Final")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Inicio")
                        .HasColumnType("interval");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UIdCatalogarAudio")
                        .HasColumnType("uuid");

                    b.HasKey("UId");

                    b.HasIndex("UIdCatalogarAudio");

                    b.ToTable("CatalogarAudioTranscricaoEntity");
                });

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioTranscricaoEntity", b =>
                {
                    b.HasOne("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioEntity", "CatalogarAudio")
                        .WithMany("Transcricaoes")
                        .HasForeignKey("UIdCatalogarAudio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogarAudio");
                });

            modelBuilder.Entity("AudioToSearch.Domain.CatalogarModels.AudioModels.Entitis.CatalogarAudioEntity", b =>
                {
                    b.Navigation("Transcricaoes");
                });
#pragma warning restore 612, 618
        }
    }
}
